#!/bin/sh

kver=${2}
bootpart=$(df -P /boot | tail -1 | awk '{ print $6 }')
bootstrip() {
	echo ${1} | sed "s,^${bootpart}/,/,"
}

cat > /boot/boot.txt <<EOF
setenv bootargs console=ttymxc0,115200 console=tty1 cma=512M pci=nomsi no_console_suspend loglevel=4 $(dracut --print-cmdline)

if load \${devtype} \${devnum}:\${bootpart} \${loadaddr} $(bootstrip /boot/disable_hdmi); then
	setenv fdtfile freescale/imx8mq-mnt-reform2-no-hdmi.dtb
else
	setenv fdtfile freescale/imx8mq-mnt-reform2.dtb
fi

if load \${devtype} \${devnum}:\${bootpart} \${loadaddr} $(bootstrip /boot/vmlinux-${kver}); then
	if load \${devtype} \${devnum}:\${bootpart} \${fdt_addr} $(bootstrip /boot/dtbs/dtbs-${kver}/\${fdtfile}); then
		if load \${devtype} \${devnum}:\${bootpart} \${ramdisk_addr} $(bootstrip /boot/initramfs-${kver}.img); then
			setenv ramdisk \${ramdisk_addr}:\${filesize}
		else
			setenv ramdisk -
		fi
		booti \${loadaddr} \${ramdisk} \${fdt_addr}
	fi
fi
EOF

exec mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d /boot/boot.txt /boot/boot.scr
